### ISSUE TITLE
Error after adding source to mx.ini

### ISSUE THREAD

**Issue by jensens** [mxstack/mxmake#17]
```
mxmake: No templates defined
Traceback (most recent call last):
  File "/home/jensens/ws/pro/akbild/portal/venv/bin/mxdev", line 8, in <module>
    sys.exit(main())
  File "/home/jensens/ws/pro/akbild/portal/venv/lib/python3.9/site-packages/mxdev/main.py", line 78, in main
    write_hooks(state, hooks)
  File "/home/jensens/ws/pro/akbild/portal/venv/lib/python3.9/site-packages/mxdev/hooks.py", line 31, in write_hooks
    hook.write(state)
  File "/home/jensens/ws/pro/akbild/portal/venv/lib/python3.9/site-packages/mxmake/hook.py", line 65, in write
    self.generate_additional_sources_targets(state)
  File "/home/jensens/ws/pro/akbild/portal/venv/lib/python3.9/site-packages/mxmake/hook.py", line 52, in generate_additional_sources_targets
    for child in os.listdir(source_folder):
FileNotFoundError: [Errno 2] No such file or directory: 'sources/collective.linguatags'
make: *** [Makefile:398: requirements-mxdev.txt] Error 1
make: *** Deleting file 'requirements-mxdev.txt'
```

**Comment by rnixx** [comment]
Fixed via [fa4c083](https://github.com/mxstack/mxmake/commit/fa4c0834df8a888a6113cd9141ee158baa56ed95)
