### ISSUE TITLE
KeyError: 'MXENV_PATH'

### ISSUE THREAD

**Issue by jensens** [mxstack/mxmake#21]
I just drop it here for further investigation
```
(pl-tfv) ~/ws/pro/tfv/kup.tfv (master*11?2s1)$ ~/ws/cdev/mxmake/venv/bin/mxmake init

#######################
# mxmake initialization
#######################

[?] Include topics: 
 > [X] applications
   [X] core
   [ ] docs
   [ ] i18n
   [ ] js
   [ ] ldap
   [X] qa
   [ ] system

[?] Include domains from topic "applications": 
 > [X] applications.cookiecutter
   [ ] applications.twisted
   [ ] applications.zest-releaser
   [X] applications.zope

[?] Include domains from topic "core": 
 > [X] core.base
   [X] core.mxenv
   [X] core.mxfiles
   [X] core.packages
   [X] core.sources

[?] Include domains from topic "qa": 
   [X] qa.black
 > [ ] qa.coverage
   [X] qa.isort
   [ ] qa.mypy
   [X] qa.test
   [X] qa.zpretty

Edit Settings for applications.zope?
[?] y/N: y
[?] applications.zope.ZOPE_CONFIGURATION_FILE: instance.yaml
[?] applications.zope.ZOPE_TEMPLATE: https://github.com/plone/cookiecutter-zope-instance
[?] applications.zope.ZOPE_BASE_FOLDER: .
[?] applications.zope.ZOPE_SCRIPTNAME: No Default

Edit Settings for core.base?
[?] y/N: n

Edit Settings for core.mxenv?
[?] y/N: n

Edit Settings for core.mxfiles?
[?] y/N: n

Edit Settings for qa.black?
[?] y/N: n

Edit Settings for qa.isort?
[?] y/N: n

Edit Settings for qa.test?
[?] y/N: y
Traceback (most recent call last):
  File "/home/jensens/ws/cdev/mxmake/venv/bin/mxmake", line 8, in <module>
    sys.exit(main())
  File "/home/jensens/ws/cdev/mxmake/src/mxmake/main.py", line 213, in main
    args.func(args)
  File "/home/jensens/ws/cdev/mxmake/src/mxmake/main.py", line 174, in init_command
    domain_settings.update(inquirer.prompt(settings_question))
  File "/home/jensens/ws/cdev/mxmake/venv/lib/python3.10/site-packages/inquirer/prompt.py", line 11, in prompt
    answers[question.name] = render.render(question, answers)
  File "/home/jensens/ws/cdev/mxmake/venv/lib/python3.10/site-packages/inquirer/render/console/__init__.py", line 33, in render
    render = clazz(question, terminal=self.terminal, theme=self._theme, show_default=question.show_default)
  File "/home/jensens/ws/cdev/mxmake/venv/lib/python3.10/site-packages/inquirer/render/console/_text.py", line 12, in __init__
    self.current = self.question.default or ""
  File "/home/jensens/ws/cdev/mxmake/venv/lib/python3.10/site-packages/inquirer/questions.py", line 82, in default
    return self.answers.get(self.name) or self._solve(self._default)
  File "/home/jensens/ws/cdev/mxmake/venv/lib/python3.10/site-packages/inquirer/questions.py", line 105, in _solve
    return prop.format(**self.answers)
KeyError: 'MXENV_PATH'
```

**Comment by rnixx** [comment]
This usually means that MXENV_PATH was not found during parsing of the existing makefile. Is it possible that you called mxmake on a project with a totally outdated makefile respective a makefile which was not generated by mxmake?

**Comment by jensens** [comment]
As this was an old version of the Makefile this is probably the cause.

**Comment by rnixx** [comment]
This should be fixed anyway

**Comment by jensens** [comment]
Hardly reproduceable. Also, it was alpha code.
